#!/bin/bash  

#pre1="/home/dressler/projects/lithium/test_chrisbase/o_line_5/create_trjek/"
pre1="../../../../../test_dir/external_ref_data/lmc_trajec_for_o_line_5/"

for arg1 in  1000 ; do
        echo $arg1
        mkdir $arg1
        cd $arg1
	for nop in 1 2 3 4 ; do
        echo $nop
        mkdir $nop
        cd $nop
	for arg2 in aimd_from_neigh_mat; do
            mkdir $arg2
	    cd $arg2
            #ln -s $pre1$arg1/$nop/lmc_final.xyz lmc_250.xyz
            cp $pre1$arg1/$nop/lmc_final.xyz lmc_250.xyz
	    cp ../../../pbc .
            create_jump_mat_li lmc_250.xyz  pbc  True  nowrap 1 H O
	    msd_from_neigh_mat jumping_ion_neighbors.npy lattice1.npy  pbc 1 2 1 
	    cd ..
        done    
	cd ..
        done
        cd ..
done

