#!/bin/bash  

pre1="../../../../../tests/external_ref_data/lmc_trajec_for_o_line_5/"
#pre1="../../../../../test_dir/external_ref_data/lmc_trajec_for_o_line_5/"

for arg1 in 1000 ; do
        echo $arg1
        mkdir $arg1
        cd $arg1
	for nop in 1 2 3 4 ; do
        echo $nop
        mkdir $nop
        cd $nop
	for arg2 in  msd_from_jump_info ; do
            mkdir $arg2
	    cd $arg2
            #ln -s $pre1$arg1/$nop/lmc_final.xyz lmc_250.xyz
            cp $pre1$arg1/$nop/lmc_final.xyz lmc_250.xyz
	    cp ../../../pbc .
            create_jump_mat_li lmc_250.xyz  pbc  True  nowrap 1 H O

            #markov_mat_from_jump_info_mat  pickle_jump_info.p 2 $nop
            markov_mat_from_jump_info_mat  pickle_jump_info.p 1 $nop

            #msd_from_markov markov_matrix_2_.txt pbc lattice1.npy 500 2
            msd_from_markov markov_matrix_1_.txt pbc lattice1.npy 500 1
	    cd ..
        done    
	cd ..
        done
        cd ..
done

