#!/bin/bash  

pre1="../../../../../test_dir/external_ref_data/lmc_trajec_for_o_line_5/"

for arg1 in  1000 ; do
        echo $arg1
        mkdir $arg1
        cd $arg1
	for nop in 1 2 3 4 ; do
        echo $nop
        mkdir $nop
        cd $nop
	for arg2 in aimd; do
            mkdir $arg2
	    cd $arg2
            #ln -s $pre1$arg1/$nop/lmc_final.xyz lmc_250.xyz
            cp  $pre1$arg1/$nop/lmc_final.xyz lmc_250.xyz
	    cp ../../../pbc .
	    #msd_from_md lmc_250.xyz  pbc  False nowrap H 1 2 1 
	    msd_from_md lmc_250.xyz  pbc  False nowrap H 1 1 1 
	    cd ..
        done    
	cd ..
        done
        cd ..
done

